import { Copy, FileText } from 'lucide-react'
import { Button } from '../ui/Button'

export interface DdlViewProps {
  ddl: string
  /** Muted caption in the toolbar. */
  source?: string
}

/** The DDL sub-view: a toolbar with copy actions above a monospace, pre-formatted statement. */
export function DdlView({ ddl, source = 'Generated by the server with DESCRIBE' }: DdlViewProps) {
  return (
    <div className="flex min-h-0 flex-1 flex-col">
      <div className="flex items-center gap-1 border-b border-line2 px-2.5 py-[5px]">
        <span className="text-muted">{source}</span>
        <div className="flex-1" />
        <Button variant="ghost" icon={<Copy size={14} />} onClick={() => void navigator.clipboard?.writeText(ddl)}>
          Copy DDL
        </Button>
        <Button variant="ghost" icon={<FileText size={14} />}>
          Open in query tab
        </Button>
      </div>
      <pre aria-label="DDL" className="m-0 flex-1 overflow-auto px-5 py-4 font-mono text-[13px] leading-5">
        {ddl}
      </pre>
    </div>
  )
}
