import { useMemo, useState } from 'react'
import { Plus, RefreshCw } from 'lucide-react'
import { Tabs } from '../ui/Tabs'
import { Button } from '../ui/Button'
import { IconButton } from '../ui/IconButton'
import { Select } from '../ui/Select'
import { ResultsGrid } from './ResultsGrid'
import { SchemaSheet } from './SchemaSheet'
import { DdlView } from './DdlView'
import { ViewsSheet } from './ViewsSheet'
import { findTable, findView } from '../mocks/schema'
import { dataColumns, dataRows, generateRows } from '../mocks/rows'
import { tableDdl } from '../lib/ddl'
import { useWorkspace } from '../store/workspace'
import type { WorkspaceTab } from '../store/workspace'

export const CONSISTENCY_LEVELS = ['ANY', 'ONE', 'TWO', 'THREE', 'QUORUM', 'LOCAL_QUORUM', 'EACH_QUORUM', 'ALL', 'LOCAL_ONE'].map((v) => ({ value: v, label: v }))

export interface TableViewProps {
  /** The table or view tab being displayed. */
  tab: WorkspaceTab
}

/**
 * Table (or materialized view) tab body with Data, Schema, DDL and Views sub-views. Views are
 * read-only and have no Views sub-view. Data comes from mock fixtures in this milestone.
 */
export function TableView({ tab }: TableViewProps) {
  const [sub, setSub] = useState('data')
  const consistency = useWorkspace((s) => s.consistency)
  const setConsistency = useWorkspace((s) => s.setConsistency)
  const open = useWorkspace((s) => s.open)
  const isView = tab.kind === 'view'
  const table = findTable(tab.keyspace, tab.object)
  const view = findView(tab.keyspace, tab.object)
  const columns = useMemo(() => table?.columns ?? view?.columns ?? [], [table, view])
  const views = useMemo(() => (table ? table.views.map((n) => findView(tab.keyspace, n)).filter((v) => !!v) : []), [table, tab.keyspace])

  const gridColumns = tab.object === 'transactions_by_merchant' ? dataColumns : columns
  const rows = useMemo(() => (tab.object === 'transactions_by_merchant' ? dataRows : generateRows(columns)), [tab.object, columns])
  const ddl = table ? tableDdl(table) : view ? `CREATE MATERIALIZED VIEW ${view.keyspace}.${view.name} AS\n    SELECT ${view.columns.map((c) => c.name).join(', ')}\n    FROM ${view.keyspace}.${view.baseTable}\n    WHERE ${view.columns.filter((c) => c.kind === 'partition' || c.kind === 'clustering').map((c) => `${c.name} IS NOT NULL`).join(' AND ')};` : ''

  const items = [
    { id: 'data', label: 'Data' },
    { id: 'schema', label: 'Schema' },
    { id: 'ddl', label: 'DDL' },
    ...(isView ? [] : [{ id: 'views', label: 'Views', badge: views.length }]),
  ]
  const pk = columns.filter((c) => c.kind === 'partition')

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      <div className="flex flex-none items-center gap-1 border-b border-line2 px-2.5 py-[5px]">
        <Tabs aria-label="Table views" items={items} value={sub} onChange={setSub} />
        <div className="mx-1.5 h-4 w-px bg-line" />
        <span className="inline-flex h-6 items-center gap-2 overflow-hidden rounded border border-line bg-editor px-2 font-mono text-[12.5px]">
          <span className="font-sans text-muted">Partition</span>
          <span className="truncate">{pk.length ? pk.map((c) => `${c.name} = …`).join(' AND ') : 'all partitions'}</span>
        </span>
        <div className="flex-1" />
        <Button variant="ghost" icon={<Plus size={14} />} disabled title={isView ? 'Views are read-only' : 'Editing arrives in a later milestone'}>
          Insert row
        </Button>
        <Select label="Consistency" value={consistency} onChange={setConsistency} options={CONSISTENCY_LEVELS} />
        <IconButton label="Refresh" icon={<RefreshCw size={14} />} />
      </div>
      {sub === 'data' && <ResultsGrid columns={gridColumns} rows={rows} elapsedMs={41} consistency={consistency} pageSize={100} onPageSize={() => {}} hasNext showCount />}
      {sub === 'schema' && <SchemaSheet columns={columns} options={table?.options} indexes={table?.indexes} />}
      {sub === 'ddl' && <DdlView ddl={ddl} source={`Generated by the server with DESCRIBE ${isView ? 'MATERIALIZED VIEW' : 'TABLE'}`} />}
      {sub === 'views' && <ViewsSheet views={views.filter((v) => !!v)} onOpen={(n) => open('view', tab.keyspace, n)} />}
    </div>
  )
}
